// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using Xunit;
public class SuiteTests : IDisposable {
  public IWebDriver driver {get; private set;}
  public IDictionary<String, Object> vars {get; private set;}
  public IJavaScriptExecutor js {get; private set;}
  public SuiteTests()
  {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<String, Object>();
  }
  public void Dispose()
  {
    driver.Quit();
  }
  [Fact]
  public void Inserirlocalinvalido() {
    driver.Navigate().GoToUrl("https://localhost:5001/");
    driver.Manage().Window.Size = new System.Drawing.Size(1051, 806);
    driver.FindElement(By.Id("login")).Click();
    driver.FindElement(By.Id("Input_UserName")).Click();
    driver.FindElement(By.Id("Input_UserName")).Click();
    driver.FindElement(By.Id("Input_UserName")).SendKeys("Wedson");
    driver.FindElement(By.Id("Input_Password")).Click();
    driver.FindElement(By.Id("Input_Password")).SendKeys("123456");
    driver.FindElement(By.CssSelector(".btn-md")).Click();
    driver.FindElement(By.LinkText("Local")).Click();
    driver.FindElement(By.LinkText("Criar")).Click();
    driver.FindElement(By.Id("Cep")).Click();
    driver.FindElement(By.Id("Cep")).SendKeys("4562");
    {
      var element = driver.FindElement(By.CssSelector(".btn-primary"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    driver.FindElement(By.CssSelector(".btn-primary")).Click();
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    {
      var element = driver.FindElement(By.Id("Cep"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).ClickAndHold().Perform();
    }
    {
      var element = driver.FindElement(By.Id("Cep"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.Id("Cep"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Release().Perform();
    }
    driver.FindElement(By.Id("Cep-error")).Click();
    Assert.Equal(driver.FindElement(By.Id("Cep-error")).Text, "Campo CEP está incompleto");
    driver.FindElement(By.Id("Uf-error")).Click();
    Assert.Equal(driver.FindElement(By.Id("Uf-error")).Text, "Campo UF é obrigatório.");
    driver.FindElement(By.CssSelector(".form-group:nth-child(3)")).Click();
    Assert.Equal(driver.FindElement(By.Id("Cidade-error")).Text, "Campo Cidade é obrigatório.");
    driver.FindElement(By.Id("Bairro-error")).Click();
    Assert.Equal(driver.FindElement(By.Id("Bairro-error")).Text, "Campo Bairro é obrigatório.");
    driver.FindElement(By.CssSelector(".form-group:nth-child(5)")).Click();
    Assert.Equal(driver.FindElement(By.Id("Rua-error")).Text, "Campo Rua/Avenida é obrigatório.");
    driver.Close();
  }
}
