// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using Xunit;
public class SuiteTests : IDisposable {
  public IWebDriver driver {get; private set;}
  public IDictionary<String, Object> vars {get; private set;}
  public IJavaScriptExecutor js {get; private set;}
  public SuiteTests()
  {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<String, Object>();
  }
  public void Dispose()
  {
    driver.Quit();
  }
  [Fact]
  public void Inserirlocalvalido() {
    driver.Navigate().GoToUrl("https://localhost:5001/");
    driver.Manage().Window.Size = new System.Drawing.Size(1552, 840);
    driver.FindElement(By.Id("login")).Click();
    driver.FindElement(By.Id("Input_UserName")).Click();
    driver.FindElement(By.Id("Input_UserName")).SendKeys("Wedson");
    driver.FindElement(By.Id("Input_Password")).Click();
    driver.FindElement(By.Id("Input_Password")).SendKeys("123456");
    driver.FindElement(By.CssSelector(".btn-md")).Click();
    driver.FindElement(By.LinkText("Local")).Click();
    driver.FindElement(By.LinkText("Criar")).Click();
    driver.FindElement(By.Id("Cep")).Click();
    driver.FindElement(By.Id("Cep")).SendKeys("49500000");
    driver.FindElement(By.Id("Uf")).Click();
    driver.FindElement(By.Id("Uf")).SendKeys("Se");
    driver.FindElement(By.Id("Cidade")).Click();
    driver.FindElement(By.Id("Cidade")).SendKeys("Itabira");
    driver.FindElement(By.Id("Bairro")).Click();
    driver.FindElement(By.Id("Bairro")).SendKeys("Carlos Alves");
    driver.FindElement(By.Id("Rua")).Click();
    driver.FindElement(By.Id("Rua")).SendKeys("A");
    driver.FindElement(By.Id("NumeroEndereco")).Click();
    driver.FindElement(By.Id("NumeroEndereco")).SendKeys("0");
    driver.FindElement(By.Id("Nome")).Click();
    driver.FindElement(By.Id("Nome")).SendKeys("Endereco");
    driver.FindElement(By.Id("Latitude")).Click();
    driver.FindElement(By.Id("Latitude")).SendKeys("0");
    driver.FindElement(By.Id("Longitude")).Click();
    driver.FindElement(By.Id("Longitude")).SendKeys("0");
    driver.FindElement(By.Id("IdOrganizacao")).Click();
    driver.FindElement(By.Id("IdOrganizacao")).Click();
    driver.FindElement(By.CssSelector(".btn-primary")).Click();
  }
}
