// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class InserirOcorrenciaInvlidaTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new RemoteWebDriver(new Uri("http://localhost:4444/wd/hub"), new ChromeOptions().ToCapabilities());
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void inserirOcorrenciaInvlida() {
    driver.Navigate().GoToUrl("https://localhost:44391/");
    driver.Manage().Window.Size = new System.Drawing.Size(1034, 700);
    driver.FindElement(By.Id("login")).Click();
    driver.FindElement(By.Id("Input_UserName")).Click();
    driver.FindElement(By.Id("Input_UserName")).SendKeys("dryele_an@hotmail.com");
    driver.FindElement(By.Id("Input_Password")).Click();
    driver.FindElement(By.Id("Input_Password")).SendKeys("123456");
    driver.FindElement(By.CssSelector(".btn-md")).Click();
    driver.FindElement(By.LinkText("Ocorrencia")).Click();
    driver.FindElement(By.LinkText("Criar")).Click();
    driver.FindElement(By.Id("DataCadastro")).Click();
    driver.FindElement(By.Id("DataCadastro")).Click();
    driver.FindElement(By.Id("DataCadastro")).SendKeys("2021-07-13");
    driver.FindElement(By.Id("DataCadastro")).Click();
    driver.FindElement(By.Id("DataCadastro")).Click();
    driver.FindElement(By.Id("DataCadastro")).SendKeys("2021-07-10");
    driver.FindElement(By.CssSelector(".x_panel")).Click();
    driver.FindElement(By.Id("Descricao")).Click();
    driver.FindElement(By.Id("Descricao")).SendKeys("Furto de um notebook na Sala 001");
    driver.FindElement(By.CssSelector(".row:nth-child(1)")).Click();
    driver.FindElement(By.Id("Descricao")).SendKeys("Furto de uma bicicleta");
    driver.FindElement(By.CssSelector(".form-group:nth-child(5)")).Click();
    driver.FindElement(By.Id("Emergencia")).Click();
    driver.FindElement(By.Id("Emergencia")).SendKeys("1");
    driver.FindElement(By.Id("IdLocal")).Click();
    driver.FindElement(By.Id("IdLocal")).SendKeys("1");
    driver.FindElement(By.CssSelector(".btn-primary")).Click();
    driver.FindElement(By.CssSelector(".btn-primary")).Click();
    driver.FindElement(By.LinkText("Voltar")).Click();
  }
}
